"""tambah kelompok tani pada jadwal tanam

Revision ID: 05cd9ecdc203
Revises: 
Create Date: 2026-06-09 16:02:25.201785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05cd9ecdc203'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelompok_tani',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_kelompok_tani',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kelompok_tani_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kelompok_tani_id'], ['kelompok_tani.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'kelompok_tani_id')
    )
    op.drop_table('hasil_deteksi')
    op.drop_table('detail_jadwal_pengelolaan')
    with op.batch_alter_table('jadwal_tanam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kelompok_tani_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_jadwal_varietas'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_jadwal_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'kelompok_tani', ['kelompok_tani_id'], ['id'])
        batch_op.create_foreign_key(None, 'varietas_padi', ['varietas_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('varietas_padi', schema=None) as batch_op:
        batch_op.alter_column('hari_penyemaian',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('varietas_padi', schema=None) as batch_op:
        batch_op.alter_column('hari_penyemaian',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('jadwal_tanam', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_jadwal_user'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_jadwal_varietas'), 'varietas_padi', ['varietas_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('kelompok_tani_id')

    op.create_table('detail_jadwal_pengelolaan',
    sa.Column('id_deteksi', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('waktu_deteksi', mysql.DATETIME(), nullable=True),
    sa.Column('jenis_input', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('url_gambar', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('teks_input', mysql.TEXT(), nullable=True),
    sa.Column('versi_model', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status_deteksi', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('catatan', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], name=op.f('detail_jadwal_pengelolaan_ibfk_1')),
    sa.PrimaryKeyConstraint('id_deteksi'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('hasil_deteksi',
    sa.Column('id_hasil', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_deteksi', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_penyakit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tingkat_keyakinan', mysql.FLOAT(), nullable=True),
    sa.Column('ringkasan', mysql.TEXT(), nullable=True),
    sa.Column('snapshot_rekomendasi', mysql.TEXT(), nullable=True),
    sa.Column('dibuat_pada', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_deteksi'], ['detail_jadwal_pengelolaan.id_deteksi'], name=op.f('hasil_deteksi_ibfk_1')),
    sa.ForeignKeyConstraint(['id_penyakit'], ['penyakit.id_penyakit'], name=op.f('hasil_deteksi_ibfk_2')),
    sa.PrimaryKeyConstraint('id_hasil'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_kelompok_tani')
    op.drop_table('kelompok_tani')
    # ### end Alembic commands ###
