"""update user

Revision ID: 31ac08d5681e
Revises: 0e8c566748b5
Create Date: 2026-04-02 22:20:56.015575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ac08d5681e'
down_revision = '0e8c566748b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fullname'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('fullname'), ['fullname'], unique=True)

    # ### end Alembic commands ###
