"""fix relasi user

Revision ID: 3ec341bb177f
Revises: d38ce665ccf5
Create Date: 2026-03-30 15:29:15.700019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec341bb177f'
down_revision = 'd38ce665ccf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail_jadwal_pengelolaan',
    sa.Column('id_deteksi', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('waktu_deteksi', sa.DateTime(), nullable=True),
    sa.Column('jenis_input', sa.String(length=50), nullable=False),
    sa.Column('url_gambar', sa.String(length=255), nullable=True),
    sa.Column('teks_input', sa.Text(), nullable=True),
    sa.Column('versi_model', sa.String(length=50), nullable=True),
    sa.Column('status_deteksi', sa.String(length=50), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_deteksi')
    )
    op.create_table('penyakit',
    sa.Column('id_penyakit', sa.Integer(), nullable=False),
    sa.Column('kode_penyakit', sa.String(length=50), nullable=True),
    sa.Column('nama_penyakit', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('penyebab', sa.Text(), nullable=True),
    sa.Column('tingkat_keparahan', sa.String(length=50), nullable=True),
    sa.Column('dibuat_oleh', sa.Integer(), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=True),
    sa.Column('diperbarui_pada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_penyakit'),
    sa.UniqueConstraint('kode_penyakit')
    )
    op.create_table('varietas_padi',
    sa.Column('id_varietas', sa.Integer(), nullable=False),
    sa.Column('kode_varietas', sa.String(length=50), nullable=True),
    sa.Column('nama_varietas', sa.String(length=100), nullable=True),
    sa.Column('jenis_varietas', sa.String(length=50), nullable=True),
    sa.Column('umur_panen_hari', sa.Integer(), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('karakterisik', sa.Text(), nullable=True),
    sa.Column('dibuat_oleh', sa.Integer(), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=True),
    sa.Column('diperbarui_pada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_varietas'),
    sa.UniqueConstraint('kode_varietas')
    )
    op.create_table('foto_hasil_penyakit',
    sa.Column('id_foto', sa.Integer(), nullable=False),
    sa.Column('id_penyakit', sa.Integer(), nullable=True),
    sa.Column('url_foto', sa.String(length=255), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('foto_utama', sa.Boolean(), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_penyakit'], ['penyakit.id_penyakit'], ),
    sa.PrimaryKeyConstraint('id_foto')
    )
    op.create_table('hasil_deteksi',
    sa.Column('id_hasil', sa.Integer(), nullable=False),
    sa.Column('id_deteksi', sa.Integer(), nullable=True),
    sa.Column('id_penyakit', sa.Integer(), nullable=True),
    sa.Column('tingkat_keyakinan', sa.Float(), nullable=True),
    sa.Column('ringkasan', sa.Text(), nullable=True),
    sa.Column('snapshot_rekomendasi', sa.Text(), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_deteksi'], ['detail_jadwal_pengelolaan.id_deteksi'], ),
    sa.ForeignKeyConstraint(['id_penyakit'], ['penyakit.id_penyakit'], ),
    sa.PrimaryKeyConstraint('id_hasil')
    )
    op.create_table('jadwal_pengelolaan',
    sa.Column('id_jadwal', sa.Integer(), nullable=False),
    sa.Column('id_varietas', sa.Integer(), nullable=True),
    sa.Column('nama_jadwal', sa.String(length=100), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('dibuat_oleh', sa.Integer(), nullable=True),
    sa.Column('diperbarui_pada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_varietas'], ['varietas_padi.id_varietas'], ),
    sa.PrimaryKeyConstraint('id_jadwal')
    )
    op.create_table('penanganan_penyakit',
    sa.Column('id_penanganan', sa.Integer(), nullable=False),
    sa.Column('id_penyakit', sa.Integer(), nullable=True),
    sa.Column('jenis_penanganan', sa.String(length=50), nullable=True),
    sa.Column('judul_penanganan', sa.String(length=100), nullable=True),
    sa.Column('dosis', sa.String(length=100), nullable=True),
    sa.Column('cara_aplikasi', sa.Text(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('urutan', sa.Integer(), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_penyakit'], ['penyakit.id_penyakit'], ),
    sa.PrimaryKeyConstraint('id_penanganan')
    )
    op.create_table('rumus_varietas',
    sa.Column('id_rumus', sa.Integer(), nullable=False),
    sa.Column('id_varietas', sa.Integer(), nullable=True),
    sa.Column('nama_rumus', sa.String(length=100), nullable=True),
    sa.Column('tipe_rumus', sa.String(length=50), nullable=True),
    sa.Column('konfigurasi_rumus', sa.Text(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_varietas'], ['varietas_padi.id_varietas'], ),
    sa.PrimaryKeyConstraint('id_rumus')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rumus_varietas')
    op.drop_table('penanganan_penyakit')
    op.drop_table('jadwal_pengelolaan')
    op.drop_table('hasil_deteksi')
    op.drop_table('foto_hasil_penyakit')
    op.drop_table('varietas_padi')
    op.drop_table('penyakit')
    op.drop_table('detail_jadwal_pengelolaan')
    # ### end Alembic commands ###
