"""update profil user

Revision ID: 991286b376c3
Revises: 31ac08d5681e
Create Date: 2026-04-04 13:15:45.358593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991286b376c3'
down_revision = '31ac08d5681e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
