from .user import User
from .riwayat_deteksi import RiwayatDeteksi
from .penyakit import Penyakit
from .foto_hasil_penyakit import FotoHasilPenyakit
from .penanganan_penyakit import PenangananPenyakit
from .varietas_padi import VarietasPadi
from .rumus_varietas import RumusVarietas
from .jadwal_pengelolaan import JadwalPengelolaan
from .detail_jadwal_pengelolaan import DetailJadwalPengelolaan
from .hasil_deteksi import HasilDeteksi