from .user import User
from .riwayat_deteksi import RiwayatDeteksi
from .penyakit import Penyakit
from .foto_hasil_penyakit import FotoHasilPenyakit
from .penanganan_penyakit import PenangananPenyakit
from .varietas_padi import VarietasPadi
from .jadwal_pengelolaan import JadwalPengelolaan
from .hasil_deteksi import HasilDeteksi
from .jadwal_varietas import JadwalVarietas
from .jadwal_user import JadwalUser